### ISSUE TITLE
Roger core, stm32duino bootloader

### ISSUE THREAD

**Issue by Sgw32** [Bakisha/STM32-SID-PLAYER#1]
Hi! 

I am trying to attach bluepill to a real C64, and I've attached PA8 via the circuit listed in a Blink example with Supremacy tune. 
Seems that everything works except first ~1 min, the sound is distorted. I am using STM32duino bootloader with USB and Roger clark core. May it cause such interference with internal IRQ?

Best regards.

**Comment by Sgw32** [comment]
Seems like the problem is in C64 audio circuit, not in blue pill. I'll try to adjust something to make it work.

**Comment by Bakisha** [comment]
I am not sure what is voltage limits of SIDs audio in , but keep in mind that output voltage of the bluepill's pin is 3.3Vpp (peak to peak). Maybe that's why you are getting distorsions. I would recommend some voltage divider, low-pass filter or at least high-capacity capacitor in series and at least some pull-down resistor (to dishcharge it).

**Comment by Sgw32** [comment]
> 
> 
> I am not sure what is voltage limits of SIDs audio in , but keep in mind that output voltage of the bluepill's pin is 3.3Vpp (peak to peak). Maybe that's why you are getting distorsions. I would recommend some voltage divider, low-pass filter or at least high-capacity capacitor in series and at least some pull-down resistor (to dishcharge it).

It works correctly, if I connect it directly to audio pin in DIN socket :D This is a temporary solution, I am just adding some functions to process C64 IO to set registers and emulate the chip. I succesfully implemented it, but seems it has some performance issues.

**Comment by Bakisha** [comment]
The "barebone" version is just SID emulation, changing global variables (with obvious names) is like POKE-ing in basic. But keep in mind that in need some time to pick up the change. In microseconds range , but still need some delays in microseconds if it's changing in some loop. You can lower it by changing initial value of variable named "multiplier" (it is fixed in barebone version).
